name: CI/CD for IoT Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Install Web App Dependencies
        run: |
          cd web_app/Source_webapp
          npm install

      - name: Install Admin Web App Dependencies
        run: |
          cd admin_web_app/Source_webapp
          npm install

      - name: Run Backend Tests
        run: |
          cd backend
          npm test

      - name: Run Web App Tests
        run: |
          cd web_app/Source_webapp
          npm test

      - name: Run Admin Web App Tests
        run: |
          cd admin_web_app/Source_webapp
          npm test


